### ISSUE TITLE
About training replication

### ISSUE THREAD

**Issue by qirui-chen** [showlab/VideoLISA#8]
Hello authors, thanks for your great work. I encountered an issue while setting up the environment. After installing `torch==2.1.0+cu121`, I am unable to import torch. It seems that a similar issue was mentioned in [link](https://github.com/pytorch/pytorch/issues/121402). Could you please double-check the correct version of torch and the installation method? Thank you.

```bash
Python 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 7, in <module>
    from .. import functional as F
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/nn/functional.py", line 20, in <module>
    from .._jit_internal import boolean_dispatch, _overload, BroadcastingList1, BroadcastingList2, BroadcastingList3
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/_jit_internal.py", line 41, in <module>
    import torch.distributed.rpc
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/distributed/rpc/__init__.py", line 74, in <module>
    from .server_process_global_profiler import (
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/distributed/rpc/server_process_global_profiler.py", line 6, in <module>
    from torch.autograd.profiler_legacy import profile
  File "/opt/conda/envs/videolisa/lib/python3.10/site-packages/torch/autograd/__init__.py", line 442, in <module>
    if not torch._C._autograd_init():
AttributeError: module 'torch.autograd.graph' has no attribute 'GradientEdge'
```

**Comment by qirui-chen** [comment]
Installing `peft=0.12.0` addressed the above issues. 

However, I found that 1) increasing batch size adds additional time cost; 2) increasing batch size will not introduce too much GPU memory cost. I was wondering whether the authors had observed similar cases, and decided to use multiple ~20G GPUs of different nodes. Thanks!

**Comment by qirui-chen** [comment]
Additionally, I want to know whether the released checkpoint on HuggingFace corresponds to `VideoLISA-3.8B (One-Token-Seg-All)` in the paper. The replicated output with performance on ReasonVOS is as follows.

```bash
Q-Size: 458

......(omitted)

VideoLISA/evaluation/reason_vos/metrics.py:32: RuntimeWarning: invalid value encountered in divide
  j = inters / union
......(omitted)

J: 0.3763731515787202
F: 0.4261801187118281
J&F: 0.4012766351452741
```

It is weird because there is almost no potential error in downloading the provided dataset/checkpoint and conducting the two-step evaluation. Would the authors be able to help point out possible reasons? Thanks.

**Comment by qirui-chen** [comment]
Please forgive me for having one more question. I noticed that the training script `train_joint.py` includes the use of the `llava_instruct_150k` dataset as a parameter, but it seems that the final model did not use it as part of the training dataset. This might also have contributed to the model's subpar performance on VQA (referencing the NeurIPS rebuttal). 

I guess the authors have experimented with including the VQA dataset as part of the training dataset. I am curious to know why the authors ultimately decided not to adopt this approach.

**Comment by JosephPai** [comment]
Hi @qirui-chen , thanks for you interests in VideoLISA.
Sorry for the late response and glad to see that you have successfully resolved the environment issue. We will update he peft version.
Regarding other questions:

1. In our experiment, we actually encountered the issue of CUDA OOM when increasing the batch size. About the time cost, yes you are correct, within the CUDA memory constraint, adding more data can greatly increase the time cost.
2. The current checkpoint is trained for 3k iterations, which corresponds to Tab. 5 and Tab. 6 in the ablation study. We will soon upload the final checkpoint, which is trained for 10k iterations.
3. The released checkpoint does not involve VideoQA data. In concept, involving VideoQA can boost the reasoning capability of the model. However, as shown in Tab. 10, involving VideoQA may cause performance fluctuation on different datasets. Therefore, we did not employ this dataset at the final version.

Feel free to let me know if you have further questions.

**Comment by JosephPai** [comment]
Hi @qirui-chen ,

We have updated the evaluation suite for image benchmarks, including ReasonSeg and refCOCO series: https://github.com/showlab/VideoLISA?tab=readme-ov-file#image-benchmarks

Regarding post-optimization, it is non-trivial to integrate XMem2 into another codebase. The best practice is to import the inference result into its codebase to have a post-optimization. Here is the guideline: https://github.com/showlab/VideoLISA?tab=readme-ov-file#post-optimization

About the problem of reproducing ReasonVOS number. We have carefully investigated the issue. The current checkpoint at huggingface is already the final version. The performance mismatch originates from the discrepancy between the cleaned code and the old data structure. We have updated the [data](https://github.com/showlab/VideoLISA/blob/main/BENCHMARK.md) and [evaluation code](https://github.com/showlab/VideoLISA/tree/main/evaluation/reason_vos). You should be able to reproduce the number reported in the paper, except for small numerical difference due to package version difference (torch, transformers, etc.)

Best,
Zechen

**Comment by JosephPai** [comment]
Hi @qirui-chen , I just updated the training script that was used to produce the final result in the paper (Tab 1, 2, and 3).
It could answer most of your questions regarding iterations, data recipe, etc.

Best,
Zechen

**Comment by qirui-chen** [comment]
Thank you for your quick reply, but the updated parameters
```
--dataset="sem_seg,refer_seg,reason_seg,vos,refer_seg_video,davis"
```
seem to no longer correspond to the part after line #L225 in `dataset.py`. This is because the dataset argument (tasks) does not seem to directly include `davis` (dataset). For example, `davis` seems to be included under the `ref_vos` task at line #330.

**Comment by JosephPai** [comment]
That's a nice catch. We used to treat Davis as an independent dataset, because it was added at later stage of the project. While during code cleaning before open-source, we re-organized it under ref-vos dataset.

**Comment by qirui-chen** [comment]
Thank you for the reply. Your responses are very helpful to me.

**Comment by qirui-chen** [comment]
Sorry to bother the author again, but I would like to ask why the phrase "Sure, [SEG]" is added to the input prompt during inference. Shouldn't this be part of the model's output? For example, [here](https://github.com/showlab/VideoLISA/blob/146f2bca25c9bba18e754bd77b1454fa27cfb6ce/evaluation/reason_vos/inference_reason_vos.py#L251-L252). 

What’s more strange is that I found adding or omitting this phrase doesn't seem to affect the model's output. The model still ends up outputting "[SEG]. <|end|>". I want to know why this happens. Thank you.

**Comment by JosephPai** [comment]
This is a teacher-forcing technique adapted from the work of LISA.
In short, if you manually append "[SEG]. <|end|>", you will enforce the model to always output a [SEG] token and then you can decode it to a mask.
If you do not apply this teaching forcing, the model will output the response by itself.
- For a well trained model, it can successfully output [SEG].
- While for a not well-trained model, it may output some other sentences that do not include [SEG] token, which will make the evaluation fail.

To ensure smooth evaluation, we adapt the teaching forcing technique same as LISA.

**Comment by qirui-chen** [comment]
Thank you for your response; it resolved my issue!!!

I would like to ask if you have encountered situations during inference where the model does not output `<|end|>` and repeats former words until =max_new_tokens. I observed this issue while training on Video QA datasets (llava-style formats), even in cases of overfitting a few samples. Additionally, I find that the eos token `<|endoftext|>` seems to be not used. 

I wonder how to use `generate()` function correctly and if you could provide some insights on this. I sincerely appreciate your help!

**Comment by JosephPai** [comment]
Both `<|end|>` and `<|endoftext|>` should be okay, as long as the model is trained with proper templates. VideoLISA is finetuned from [this model](https://github.com/mbzuai-oryx/LLaVA-pp), so the chat template and EOS (or EOT) token are also adapted from there.
The reasons of not outputting `<|end|>` can be multifactorial, you may need to check the `conv_template`, pre-processing function, and loss curve, etc.

**Comment by qirui-chen** [comment]
Thank you for your response.

**Comment by Lexarymade** [comment]
> Thank you for your response.

hi, i've encontered the same <|end|> issue, have you fixed this?

**Comment by qirui-chen** [comment]
> > Thank you for your response.
> 
> hi, i've encontered the same <|end|> issue, have you fixed this?

Hello, I think this issue is likely caused by the author rewriting the `forward` function, which resulted in the `attention_mask` parameter being absent in the `forward` function. This parameter is related to the underlying logic of the `generate` function in `transformers`, particularly the handling of `position_ids`.
